# Generated by Django 5.0.4 on 2024-04-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categories",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
